export default {
  MAX_PLAYERS: 6,
  MAX_HEARTBEAT_INTERVAL: 5000,
  CHECK_CONNECTION_INTERVAL: 500,
  SEND_STATE_INTERVAL: 250,
  TIME_TO_CHOOSE_ROLE: 30000,
  TIME_TO_VOTE_JOURNEY: 30000,
  TIME_TO_VOTE_SPY: 60000,
  TIME_INTERVAL: 1000,
  HOST_ID_PREFIX: "tic-tac-toe-cast",
  HOST_ID_LENGTH: 6,
  STATE_LABEL: "STATE",
  GAME_STATE: {
    PLAYERS_CONNECT: 0,
    MAKE_MOVES: 1,
    GAME_REVIEW: 2,
  },
  COLORS: {
    BLACK: "#222222",
    WHITE: "#DDDDDD"
  },
  MESSAGE_TYPES: {
    HEARTBEAT: "HEARTBEAT",
    DISCONNECT: "DISCONNECT"
  }
};
